---
title: "Haslet"
date: 2017-07-12T12:54:26-04:00
draft: false
type: recipe
tags: "Recipes"
---
=== Haslet

Quick post with a recipe for Haslet, I’ll clean it up later with some pictures and more information.

* 1lb sausage meat
* 1lb of liver (traditionally beef or lamb)
* 2 large Onions
* 1 cup breadcrumbs
* Fresh Sage & Thyme / Parsley / Nutmeg, optional all spice
* 300ml Milk soaked into 5 slices white bread
* 2 eggs
* Season to taste (salt / pepper / small amount of nutmeg)

I like English bangers which are hard to find over here so I use any sausage meat and generally add some rough chopped sage to it. For the liver, if you go with lamb or beef, soak it for a while in Milk to get rid of the bitterness. Or use chicken liver which I find works well.

Cook the liver for about 3-5 minutes then combine it with the sausage meat in a mixer and mix it really well. Roughly chop the onions and mix that in with the breadcrumbs. You end up with a sticky mixture similar to an American meatloaf recipe.

I use a loaf tin and cover it with tin foil with a couple of small holes, and bake it for about an hour to 2 hours, on 425 covered and a further 30 with the foil removed to brown it off.

When it’s done, take it out and I normally drain off some of the fat at this stage, but leave it to cool before transferring it to the fridge.

It came out exactly as I remember it, when I first had some, it took me back to being a kid again this is a taste of my childhood.
